# Generated by Django 5.2.4 on 2025-08-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDay',
        ),
    ]
