# Generated by Django 5.2.4 on 2025-08-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='expires_at',
        ),
    ]
